### ISSUE TITLE
extend evse.uid to at least 36 characters of length

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#112]
I feel our uid definition was too closely based on DB auto-increments.
If an operator wanted to use UUIDs here, for instance, he'd be in trouble. With 36 chars, the UUID canonical form would be usable as evse.uid that's why I propose to change the type from string(15) to at least string(36)

**Comment by simonschllng** [comment]
Then make it string(48) to allow for EVSE-IDs as well.

**Comment by ahzf** [comment]
@poohsen Yes, I think OCPI is still far too much a JSON representation of a SQL schema. As a protocol _openness_ and being strict on what you send, but relaxed on what you accept, is key to become widely accepted and future proof. Thus removing all length limitations would be a good start. I could for example imagine to use crypto certs or other very long "strings" as an UID directly instead of hashing them down to 10-20 characters.

The only reason for limits I can imagine is _security_ on the receiver side. Thus adding some general text to the OCPI specification like: "Better check twice before accepting a message having a 2k UID" would be a good thing.

**Comment by poohsen** [comment]
the problem is that this UID is supposed to form part of the URL for that EVSE and then you're bound by the de facto limit for URLs of ~2000 characters so I think string(48) might be the best for now

**Comment by poohsen** [comment]
i created PR #113 
there actually already was a PR by EVBox requesting an upgrade to 36 in May. I totally missed that.
I think 48 is more future proof, though.
