### ISSUE TITLE
pagination section needs to talk about guarantees

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#117]
pagination is quite a tricky functionality to implement on the server side if you want to guarantee that a client traversing the pages will see all the data and no duplicates. I would argue that our specification implies that those two guarantees are given by not talking about them at all. We should be more specific.
I propose to allow for both phenomena and let the clients deal with it but I'd like to hear opinions on this

**Comment by RobertdeLeeuw-IHomer** [comment]
Good point, I think I understand your concerns. 
What happens when objects being added while a client is traversing the list by using the "next" link??

Does this depend on the server side implementation? I would propose the following:  Start with the oldest object, give that offset = 0.  When you give new objects the highest "offset", then the sequence of objects should never change, only the last "page" will be different when you would request it again after an object has been added...

Should we add some text to explain this?

**Comment by RobertdeLeeuw-IHomer** [comment]
I have added some text to explain this and how it should be implemented, hope that is clear.
