### ISSUE TITLE
Security problem: Cannot hash / encrypt tokens

### ISSUE THREAD

**Issue by kiequoo** [ocpi/ocpi#130]
In the Credentials module, I would expect to hash the tokens of other parties before storing them in our DB.  However, part 7.11 of the spec says 

```
7.1.1 GET Method
Retrieves the credentials object to access the server’s platform. The request body is empty, the response contains the credentials object to access the server’s platform. This credentials object also contains extra information about the server such as its business details.
```

The response also includes a mandatory field which is the token of the other party.  This means we need to store it in the DB unencrypted, which is very insecure.

This field should not be included on the GET response as the caller already had to provide it to access the endpoint.  This means we could then store the token encrypted in our DB, and the system would be more secure.

**Comment by bramus** [comment]
You can, actually:

- `GET /credentials/`: Send back the `token` as found in the `Authorization` header. Since the request succeeded the `token` is valid. 
- `POST /credentials/`: Send back the generated `token`, then store a hashed version.
- `PUT /credentials/`: Send back the generated `token`, then store a hashed version.

**Comment by kiequoo** [comment]
@bramus Very true, thanks!
