### ISSUE TITLE
Version 2.1.1 or 2.1

### ISSUE THREAD

**Issue by JaZo** [ocpi/ocpi#143]
I'm currently implementing an OCPI system and there is some confusion amongst me and some partners about the 2.1.1 version. Version 2.1.1 is present in the example data of the version information endpoint and I would assume that I can respond with that version. However, some partners recall that in some meeting it was decided to report version 2.1.1 as 2.1. This sounds very confusing to me because this basically 'breaks' the versioning system. Besides, this decision is nowhere to be found in the documentation. It even states "OCPI version 2.1. (DEPRECATED, do not use, use 2.1.1 instead)". Can someone please clarify this?

**Comment by JaZo** [comment]
@RobertdeLeeuw-IHomer, can you clarify this?

**Comment by poohsen** [comment]
To my knowledge, 2.1 _is_ deprecated and should not be used to "report" version 2.1.1. This is our (NewMotion) point of view and it's been confirmed by @mbayings in the Slack group, unless I misunderstood.

That said, in our /versions endpoint, we now have both, 2.1.1 and 2.1, because we already had a party connected to 2.1 and didn't put in the effort to move that to 2.1.1 (even though this should not involve any work for the modules in question).

As a general note, the versioning is confusing. We wanted 2.1.1 to "bugfix the spec", i.e. clarify what was unclear or confusing and not introduce anything new or change existing stuff, but we ended up changing identifier lengths, which can mean that messages from a 2.1.1 module will contain identifiers too long for a 2.1 module. And of course we software devs are used to semver and backwards compatibility of libraries to their minor versions. In hindsight, 2.1.1 should've been called 2.2 but there were already expectations what 2.2 would deliver while we needed to quickly address the short identifier lengths and so this made it into 2.1.1

I guess that from an implementation perspective, 2.x.y should not be expected to be compatible with 2.x.y-1 in OCPI. But you can expect the implementation work for going from 2.x.y-1 to 2.x.y to be small, while going from 2.x to 2.x+1 would entail more work.

I hope we will make do without bugfix versions in the future.

**Comment by RobertdeLeeuw-IHomer** [comment]
2.1 is deprecated. Meaning that it should no longer be used. It is replaced by 2.1.1.  
2.1 is not compatible with 2.1.1.

If you have working 2.1 implementations/connections and don't have problems with the known bugs, you can still keep using them, but I would never advice to implement it or start using it for a new project.

**Comment by JaZo** [comment]
Thanks for the extensive answers, I totally agree!
