### ISSUE TITLE
OCPI needs support for German "Eichgesetz"

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [ocpi/ocpi#159]
German legislation requires some strict signing of values to prove they are from an accurate meter.
OCPI might need support for thsi.

**Comment by simonschllng** [comment]
Yes, might. I'm on the topic and will keep you updated.

**Comment by RobertdeLeeuw-IHomer** [comment]
Do we also need a way to send the certificate, that can be used to verify the signing from the Charging Station (and/or CPO) to the MSP?

**Comment by simonschllng** [comment]
There are no certificates. Key-pairs only. The pubkeys are published on a central register or can be read from the CP.

**Comment by ahzf** [comment]
@simonschllng Well, **currently** there are no certificates for the public keys of smart meters, but this is more based on the fact that neither the PTB, nor most Smart Meter vendors know what they are doing in crypto.

When you want to use crypto in a less insane way you want:

1) An OCPP command to trigger the creation of a (new) public key of the smart meter

2) An OCPP command to read the current public key

3) The ability in the CPO backend to add some meta data to the public key... like , "EVSE Id", "ChargingStationId", "ChargingPoolId", ... and "not before", "not after" because you have to deal with future key roations.

4) At least one CPO public key which can sign all Smart Meter public keys and their meta data. Perhaps a CPO might use more than one public key... one for its identity, one for daily usage, one for signing Smart Meter keys, ... this up to the CPO. Only this gives you an end-to-end security chain.
Of course these CPO public keys should be signed by e.g. trusted 3rd parties like Hubject or in a p2p-way like PGP/GPG. Of couse EMPs also have public keys.

5) Only signed Smart Meter public keys are published:
a) On the website/API of each CPO
b) In a central registry like BNetzA, Hubject, or something else...
But this registry must just be a cache for easier lookup. It must not break the end-to-end security chain.

6) All signed Smart Meter meter readings must be verifyied within the CPO backend.

7) We need OCPI messages like "Charging Session Created", "Charging Session Update" and "CDR" which not only allow to send signed meter readings to EMPs and end users, but also to add additional meta data to this charging session/cdr. This again has to be signed by at least one CPO public key. Before those data is send the the enduser it must also be signed by the EMP public key.

8) The most positive thing here is: This will make the German Eichrecht just an application of basic crypto protocols, therefore it will be so simple that you can easily tell S.A.F.E., htb, ebee and the others: Go back to hell! :)

_And yes, it would also be nice if Smart Meter vendors would sign the public keys their Smart Meter have created, but I guess this is from a security point of view just not possible to do without relying of security-by-obscurity._
