### ISSUE TITLE
Identify connector on start session

### ISSUE THREAD

**Issue by pandaGaume** [ocpi/ocpi#183]
Hello,
I wonder how 

- we can specify a specific connector id when starting a session. 
- we can track the corresponding flow startSession command  vs Session put to emsp

The reason is many CPO has implemented the esve as unique container of connector.
if we send multiple startSession to a single evse, we suppose to obtain multiple async response from cpo with PUT session messages.. but we do NOT have user information it can bind a specific startSession message to a specific PUT session message.. Anything i missed in the doc ???

**Comment by RobertdeLeeuw-IHomer** [comment]
No, you cannot specify a specific connector. When an EVSE has multiple connectors, you can only charge at one of the connectors of the EVSE, I have not seen Charging Stations with more then 2 connectors per EVSE yet. 
See: https://github.com/ocpi/ocpi/blob/master/mod_locations.md#3-object-description

If you send multiple START_SESSION commands, you cannot determine which request resulted in the Session being started. Problem was in the lower layers, OCPP 1.x did not support a binding. Now with OCPP 2.0, there is a "remoteStartId" which can be used for binding. This could be added to a new version of OCPI.

**Comment by angaaron** [comment]
@RobertdeLeeuw-IHomer i've seen some EVSE that have multiple connectors and can charge at them simultaneously. Do you have any advice handling this? as a EVSE according to OCPI it can only control one connector at a time.

**Comment by RobertdeLeeuw-IHomer** [comment]
@angaaron then you do not understand the definition of an EVSE. An EVSE is not the same as a Charge Point, it is a part of the Charge Point. 
A Charge Point has one or more EVSEs. An EVSE has one or more connectors. 
When a Charge Point can charge on more then 1 connector, it has more then 1 EVSE.

**Comment by angaaron** [comment]
I see, coming from an OCPP perspective where the Charge Point only has one Charge Point ID(but can control two connectors at once) and OCPP status connector messages come through as connectorId 1 & 2. To transfer this to OCPI would it make sense to create two EVSE's with unique id's & the same evse_id's for both that matches the Charge Point ID? And only have one connector for each? Cheers @RobertdeLeeuw-IHomer

**Comment by jirouette** [comment]
Hello, 

I'd like to restart this discussion. As a CPO, identifying the correct connector to target is one of my main issues with `START_SESSION`. Here is why : 

- I have many charging stations with multiple connectors (sometimes 3 per EVSE, in average 2 per EVSE)
- We're still in OCPP1.X (started with OCPP1.5, now slowly deploying OCPP1.6 chargers)
- Most of them need to target a specific connector and won't allow to use another one

In my case, when receiving a `START_SESSION`, I have no other choice but to arbitrary target a `connectorId`, but I'm not able to confirm that this is the connector the end-user wanted to use. 

An interesting feature for OCPI 3.0 would be to let the end-user (through its eMSP) select the features he'd like to have when sending a `START_SESSION`, even without specifying an EVSE. 

It would be something like : 
- `ConnectorType`
- `ConnectorFormat`
- or even voltage/amperage/`PowerType` combo

For example, and end-user would send a `START_SESSION` needing : 
- A `DOMESTIC_F` or a `IEC_62196_T2` type
- A `SOCKET` format
- A power of >22kW

Depending on the needs of the end-user, the CPO would launch an appropriate `RemoteStartTransaction.req` in OCPP if any of the EVSEs of the location correspond (or the one targeted with `evse_uid`). 

Even though my example is using OCPP, this proposal is not dependant of it. It allows an eMSP to restrict a `START_SESSION` to specific requirements.

**Comment by RobertdeLeeuw-IHomer** [comment]
@jirouette: How do you currently represent the OCPP 1.5/1.6 that have EVSEs with multiple connectors in OCPI? In case of a OCPP 1.x Charge Point, I think, it is best way to represent such a Charge Point is make them 1 EVSE and 1 connect in OCPI. This way all the commands that work on EVSE level work. For OCPP 1.x there is an ApplicationNote how to implement a Charge Point that has multiple connectors per EVSE. Might be good to do a simular thing for OCPI.   

I always see 2 use cases:
- The driver wants to start charging on a specific connector (and thus EVSE) when EV already parked.
- The driver wants to select an Connector/EVSE based on some preferences, that will be always before parking, so at a central terminal or during reservation.

**Comment by jirouette** [comment]
@RobertdeLeeuw-IHomer I represent EVSE as the number of vehicles which can start a charging process at the same time, as suggested by eMI3 and even OCPI. Each EVSE may have multiple connectors, but only one is usable at the same time. However, connectors may have different attributes (such as power, format, type, or even tariff). 

Your suggestion would be difficult to implement, because an end-user may believe there are plenty of chargers in this area (even if I dynamically toggle `INOPERATIVE`/`AVAILABLE` status to these EVSEs). 

In fact, this implementation is technically independant of the protocol. The only issue is that some chargers need to target a connector to start a session. Based on this constraint, I believe this feature would be interesting even if not needed by every chargers, as optional filters. 

I'm not sure I see the ApplicationNote for OCPP 1.x you're mentionning. Could you please tell me more about it ?

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that that is the best way to do it, but we have an issue with the limitation of OCPP 1.x. 
If we would make changes to OCPI to fix the issue with OCPP 1.x, might be the wrong way around.

I cannot find the ApplicationNote on the OCA Website at the moment. It seems not available on the new website.

**Comment by jirouette** [comment]
>  If we would make changes to OCPI to fix the issue with OCPP 1.x, might be the wrong way around.

Yes, that's why my proposal is more of a value-added feature for the end-user rather than a fix. When sending a `START_SESSION` without specifying the EVSE (only the Location), the CPO would have the choice to launch it on any EVSE corresponding to the filters the end-user needs and depending on its own constraints (would it be OCPP 1.x issue or something else, like smart charging, power management, reservation, access, schedule, pricing, etc.). It would also work if an EVSE is targeted, simply adding one more filter from the end-user. 

This is also why I didn't propose to simply use the `connector_id` in the `StartSession` object, because I agree that it does not suit OCPI. (Even though I did this quick fix in a custom `commands`-like module for internal requests from my eMSP platform to my CPO platform for the time being :grimacing: )

___________________

About OCPP : 

OCPP 1.x does technically provide a way to send a `RemoteStartTransaction.req` without specifying any connector (as it is optional, even though the charger may refuse since 1.6). This means a charger could accept to start a session without targeting a connector, but most of the ones I supervise as a CPO won't, because the manufacturer simply didn't want to implement it. There are a few exceptions, but most of the 180 references from 20 manufacturers I handle work this way. At this moment, from our side, we don't see any manufacturer pushing OCPP 2.0, meaning we'd still have to wait several years before it begins to be deployed, meanwhile OCPP 1.x chargers would still be deployed. 

I recognize that OCPP 2.0's `RequestStartTransaction.req` does correctly handle EVSEs, but as for OCPP 1.x, I'm expecting different behaviours depending on the manufacturer. 

The fact is that charger manufacturer's implementations are erratic and difficult to make evolve (hardware constraints, many chargers to upgrade, chargers which cannot be upgraded anymore, will of the manufacturer, etc.) while OCPI implementations are centralized through partners' servers. So, this whole issue does not come from OCPP but from the high number of charger references. 

How CPO handles the discrepancy of having chargers which would or would not allow a remote start without a connector is at the discretion of the CPO, depending on the contraints on both OCPP, OCPI or other network protocols. Trying to remove constraints from any side would be great.

**Comment by RobertdeLeeuw-IHomer** [comment]
We could at a connectorId to OCPI 2.2. But would a CPO do when he has to send a RequestoinStartTransactionRequest to an OCPP 2.0 Charge Point with a connectorId, which is not available in OCPP 2.0? 

I dont known all the chargers in the world, but I have only seen DC Fast Chargers that have multiple connectors per EVSE. I have not yet seen this in AC Chargers. So in my view, this is a DC Fast Charger issue. I I think that OCPP 1.x is not well designed for such chargers, and I would think that manufacturers of these more expensive chargers will be the first to move to OCPP 2.0. 
I agree, that I dont expect a lot of existing AC Chargers will get OCPP 2.0 firmware, controllers might be too small to handle all the new functionality. 
So yes, the existing DC Fast Chargers don't have OCPP 2.0 are the issue here. If these chargers would be reported as 1 EVSE per Connector over OCPP 1.x, they will show as lot more charging stations, as you said. But I don't think that is such a big issue, because these will have different connector types. So for 1 EV driver, he only sees 1 usable connector/EVSE. The other connectors are not usable to a driver. And as OCPP prescribes that all the other connectors should go to no longer available. So other drivers will known that the connector they would want to use is also not available....

But still, if we can find a solution that will work with both OCPP 1.x and 2.0 charging station, I'm open for it. Would it work if we:
- add the connetorId, as optional field?
- when not provided, but is needed for a OCPP 1.x Charge Point., CPO can reject the request with a specific error? 
- If connectorId is provided, but Charge Point is OCPP 2.0? CPO can ignore the connectorId? (I think rejecting would be worse, then the eMSP needs to resend the same request without the connectorId.)

I would sometimes be useful of the  eMSP would known the OCPP version in these kind of situations, but I dont like mixing knowledge of a lower level protocol into OCPI.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added description for this in: https://github.com/ocpi/ocpi/commit/f4820f366052a1dbc8a30e12acbff94f78b8f44b
