### ISSUE TITLE
Sequence diagrams for START_SESSION contradict interface definitions

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#184]
The immediate response from the CPO is simply shown as "SUCCESSFUL" in the diagrams, whereas the response data as per chapter 13.2.1.2.1 is defined to be of type `CommandResponseType` which does not contain a value "SUCCESSFUL". The response should be equal to the body of the asynchronous  response sent by the CPO at a later stage.

A second observation is that in the START_SESSION example where the EV is not plugged in the asynchronous response is still SUCCESSFUL. Is this really the behaviour we want? Are CPOs expected to queue session starts for some period of time until they time out? This behaviour is not specified anywhere except for the sequence diagram. 

Wouldn't most chargepoints reject the start if no cable was plugged in, which would result in an async CPO response rejecting the MSP's START_SESSION? This would be a second issue with the sequence diagrams.

**Comment by RobertdeLeeuw-IHomer** [comment]
Oeps, you are write, sequence diagrams should have contained: ACCEPTED.

You mean the sequence diagram: 
https://github.com/ocpi/ocpi/blob/master/data/command_start_session_timeout.png

I looked at OCPP, there it is possible to send a RemoteStartTransaction/RequestStartTransaction without the  EV being connected, I know there are Charging Stations, especially fast chargers where the cable is locked in the holster, until a driver is authorized. This can then also be the RemoteStartTransaction.

The RemoteStartTransaction will then result in successful, but, in this case, when the EV is not plugged in, in-time, there will never be a transaction started. 
With OCPP 2.0, it is now possible to connect the RequestStartTransaction with the transaction that is really started. I would propose to add some functionality in a newer version of OCPI to have this 'RequestId' somehow working in OCPP and OCPI. That makes it a lot easier for the eMSP, but is has to be optional because not al Charging Station in the field are OCPP, and not all will be OCPP 2.0.
