### ISSUE TITLE
OCPI 2.2 release but not on github?

### ISSUE THREAD

**Issue by dorpsidioot** [ocpi/ocpi#208]
On the site: https://www.nklnederland.com/news/official-release-ocpi-version-22/ it states that OCPI 2.2 is officially released, but the github repo seems untouched? Why is this?

**Comment by simonschllng** [comment]
Probably because of the way the nkl thinks of open source. Unsure if this violates the licence grant 1.B.

I don't like it either.

**Comment by ahzf** [comment]
I could not agree more. Sad to see, that some people with commercial interests intentionally or accidentally kill such a great project.

**Comment by drgorb** [comment]
the right solution would be to download the new version and create a PR

Anyone up for this?

**Comment by RobertdeLeeuw-IHomer** [comment]
2.2 is not yet officially release, it is still a release candidate, it is on github:
[https://github.com/ocpi/ocpi/releases](https://github.com/ocpi/ocpi/releases)

As it is not yet released, the source is still in the develop branch: [https://github.com/ocpi/ocpi/tree/develop](https://github.com/ocpi/ocpi/tree/develop)

**Comment by dorpsidioot** [comment]
Then why does nkl state that it's released? Been having some questions around our implementation timeline for it from our clients which are linked to eViolin.

I'm going through the 2.2 release as we speak

**Comment by mbayings** [comment]
OCPI v2.2 is released as RC 1. You see it also at the OCPI-protocol website if you download the version with RC1 to it. On the NKL and OCPI website we indeed anounce it as official release as we believe it is a release that is published. And this version is also available on Github as all versions will be and are available on Github. 

We have a tight schedule because of agreements with projects that support OCPI development, which result in the situation that we do not have time to make v2.2 a full final release, but need to keep it a Release Candidate now. Mid this year we want to have a draft v3.0. And then we must look TOGETHER with the community which version they want for their main implementation.

As v2.2 RC1 solves several issues we discovered with 2.1 and v3.0 will be a more radical change with the module setup, there is a good possibility that most companies will keep the implementation focus on v2.2. And that might result in a RC2 if needed. 

Complains can be mentioned but Contributions are much more appreciated. 

Every one that signs the IPR policy (free of charge) can contribute directly.

**Comment by epieters** [comment]
> OCPI v2.2 is released as RC 1. You see it also at the OCPI-protocol website if you download the version with RC1 to it. On the NKL and OCPI website we indeed anounce it as official release as we believe it is a release that is published. And this version is also available on Github as all versions will be and are available on Github.

As long as OCPI 2.2 is an RC, it is not officially released. It's as simple as that. Don't beat around the bush and regardless of what you (NKL / OCPI website) believe, there are well-defined rules on versioning, including ALPHA, BETA, RC, ... Please stick to them instead of using your own interpretation. 
The announcement should have been that OCPI v2.2-RC1 is released.

(This is a contribution and not a complaint ;-) )
