### ISSUE TITLE
Authorization token and base64 

### ISSUE THREAD

**Issue by labtrax** [ocpi/ocpi#212]
Hey together, 

short question about the Ocpi identifying token: Should that be base64 encoded or not? There's nothing in the specs about base64, but some official http authorization headers require base64, so I'm not sure, also some partners seem to do this, some not...

Thanks in advance for answering
Malte

**Comment by RobertdeLeeuw-IHomer** [comment]
Hi Malte,

This is the first time I hear this question. but you are right, specification is not clear on this point. We have done a number of OCPI implementations, both CPO and eMSP, have connected with a lot of parties and both Hubs that support OCPI, we have never used base64 encoding for the token. So, no, it should not be base64 encoded. The token provided should be used as is. I don't see a reason why base64 encoding would be needed. It does not add any extra security. I will add a remark to OCPI 2.2 to make this more clear.

**Comment by labtrax** [comment]
Thank you for the very quick reply! 
Initially we did not implement this because it not mentioned in the docu. But our first partner did, so I was wondering a bit but implemented it because the partner already had another partner. I just wanted to have this like a bit more official and to avoid disscussions.

**Comment by ahzf** [comment]
The current https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/transport_and_format.asciidoc says the exact opposite: "Its parameter is a string consisting of printable, non-whitespace ASCII characters. It contains the 'credentials token' Base64 encoded."

So what is more "correct"?

**Comment by RobertdeLeeuw-IHomer** [comment]
@ahzf  Is there a contradiction in that text? Base64 encoded information is normally always "printable, non-whitespace ASCII characters"

**Comment by ahzf** [comment]
I faced the following problem: A partner tells you, that your access token is "12345678", what do you now see on the HTTP layer?

`Authorization: Token 12345678`
or
`Authorization: Token MTIzNDU2Nzg=`

The partner could also argue that my access token is "MTIzNDU2Nzg=".

So what is the access token on the HTTP and what is it on the "human" layer? I would read the specification that there is a base64 encoding/decoding between HTTP and humans.

**Comment by tomkuijsten** [comment]
@ahzf good question!

There is a big contradiction between 2.1.1/2.2 and 2.2-d2, where the latter explicitly makes the base64 encoding a must (while the other docs don't mention it at all). In practice, we got the following situation: we received a token A and the versions url from a partner, but now we have to guess whether they use Base64 encoding or not. Our solutions now is "try both", which is silly.

It's too late now to fix this in the docs, because everybody is implementing it differently now.

**Comment by RobertdeLeeuw-IHomer** [comment]
I think that every softwate engineer that has used HTTP Basic Auth will recognize te given example: "Authorization: Token IpbJOXxkxOAuKR92z0nEcmVF3Qw09VG7I7d/WCg0koM="
As HTTP Basic Auth, thus using base64 encoding. Just not using User name password but Token based authentication. Yes, that was not explicitly described in OCPI 2.2 and before. We improved the documention in 2.2-d2.

If you are in doubt about what the other party is giving u, ask them. I always expect it to be NOT base64 encoded, but if it looks base 64 encoded to me, I will check with the other party. We store them not Base64 encoded in the database.

**Comment by maurerle** [comment]
As I read the specs the Communication for the Credentials module states explicitly:
"The credentials token for the other party to authenticate in your system. Not encoded in Base64 or any other encoding."
(https://github.com/ocpi/ocpi/blob/master/credentials.asciidoc#131-credentials-object)
In contrast to the transport and format:
https://github.com/ocpi/ocpi/blob/master/transport_and_format.asciidoc#112-authorization-header
where it says that the header "contains the 'credentials token' Base64 encoded".

The situation is still far from clear to me, what's preferred by the specs.
I'd expect this to be plain in the credentials module but additionally base64 encoded in the Authorization Header.

But as you said, this is not expected, so maybe the specification should be more explicit.

It seems that mod_credentials uses base64 as the encoding mechanism and the transport module uses the word as "printable, non-whitespace ASCII characters". So maybe it should state "printable, non-whitespace ASCII characters, (for example base64 encoded if needed)"

**Comment by RobertdeLeeuw-IHomer** [comment]
@maurerle 
"I'd expect this to be plain in the credentials module but additionally base64 encoded in the Authorization Header."

Where are you reading something differently? Where could we improve?

**Comment by maurerle** [comment]
You said in the comment above:
>  I always expect it to be NOT base64 encoded

I thought that would include that you would expect the authorization Header to be plain text.
This contradicts to the specs, which state that the authorization header should be (additionally) Base64 encoded..?

**Comment by RobertdeLeeuw-IHomer** [comment]
@maurerle that comment was about the Credentials Token "A" your receive via email or some other form of communication. I would expect that NOT to be base64 encoded.

**Comment by ahzf** [comment]
Basically, OCPI was different in the past and the specification was never updated 100%.

Just implement it in the following way:
- You agree any string with your communication partner, e.g. "hello world"
- Before putting it into the HTTP Authorization Header apply base64 encoding.
- When you receive an OCPI message use base64 decoding

And of course the entire credentials module is broken by design. You always have to agree with your communication partner its CountryCodes, PartyIds and Roles out-of-band. So best idea is to think of "CountryCode+PartyId+Role" as your login and the credentials token as your password. Do not reuse the "password" for different roles, parties or countries.

Currently the OCPI specification allows the client to choose its identity and roles... which is just the total absence of IT security in OCPI ;)
