### ISSUE TITLE
How do you PATCH the right token in 2.1.1?

### ISSUE THREAD

**Issue by tomkuijsten** [ocpi/ocpi#306]
In 2.1.1 we have the token types RFID and OTHER. When we receive a PATCH for a token, how do we know if it's a RFID or a OTHER type? The uid is not unique within the MSP system, only in combination with the type.

**Comment by ahzf** [comment]
Is there any good excuse why a "unique identification (uid)" is not unique in your/the EMSP system?

**Comment by RobertdeLeeuw-IHomer** [comment]
@tomkuijsten you cannot be sure. That is why we fixed this in 2.2. 

But as @ahzf stated. It is almost impossible to have two tokens with the same uid where one is an RFID and the other is of type OTHER. The RFIDs have a very specific format.

**Comment by tomkuijsten** [comment]
> Is there any good excuse why a "unique identification (uid)" is not unique in your/the EMSP system?

Because the spec tells me it's not unique, only in combination with the token type. But as @RobertdeLeeuw-IHomer said, it is possible, but not very likely that an MSP uses the same UID for RFID and OTHER. I guess it's up to the MSP to use unique uid's, even without the token type. Thanks for the answers.

**Comment by ahzf** [comment]
Yes you are right... but this is clearly just a flaw in the documentation.

I guess this part was written by some SQL-fan, because in SQL it is common to use multiple data/columns to create uniqueness, but in the modern world of Internet applications we normally use explicit uniqueness.

The same is true for the EVSEUIds vs. EVSEIds. Please just use the standardized EVSE format for both values. Nobody wants to see your SQL-row-ids within a roaming protocol. Reusing EVSE Ids without a quarantine of 6-12 months does not work within the shared and seldom updated state of a protocol within the Internet.

**Comment by thanaParis** [comment]
Could I get a clarification on this? The spec doesn't actually 'tell me it's not unique' as far as I can see--in fact, it seems as though the description of _uid_ (`Unique ID by which this Token can be identified`) and the _note_ under the Token Object definition (`The combination of uid and type should be unique for every token within the eMSP’s system`) either disagree with each other or are problematically vague.

If OCPI does not mandate that Token _uid_ is unique, I would end up storing Token objects under an id of `uid+Token.Type`, which seems to me a needless complication. Looking at the Cdrs module, it has a similar issue with Credit Cdrs, and rather than having Cdr _id_ only be unique in combination with the value of _credit_, it specifies for the id to be extended. Something similar should work for all use cases with Tokens?

**Comment by RobertdeLeeuw-IHomer** [comment]
@thanaParis are you looking for what to use as keys in your database? Add a unique key for that, dont use the fields received from OCPI. The same `uid+Token.type` combination might be used by different MSP, so it is only unique for each MSP.

**Comment by thanaParis** [comment]
That's a good point, thanks--I hadn't considered that.

Regarding the description of the field in the spec: can the same `uid` be used for a different `Token.type` by the same MSP? If so, I do think the description should be modified to mention this, because then it is not a `Unique ID by which this Token can be identified`.

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that the description could be improved.  I propose: 'Unique ID by which this Token, combined with the Token type, can be identified.'

**Comment by thanaParis** [comment]
That description works perfectly I think: #349
