### ISSUE TITLE
Unclear phrasing about tariff start_date_time and end_date_time

### ISSUE THREAD

**Issue by OskarD** [ocpi/ocpi#326]
https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#131-tariff-object

In the note about `start_date_time` and `end_date_time`:

> When the Tariff of a Charge Point (Location) is changed during an ongoing charging session, **it is common to not switch the Tariff** until the ongoing session is finished. But **this is NOT a rule of OCPI**. When charging at a Charge Point, a driver accepts the tariff which is valid when they start their charging session. If the Tariff of the Charge Point would change during the charging session, **the driver might get billed something they didn’t agree to** when starting the session.

_(I have highlighted the significant parts)_

Here is what I can understand from this:
1. The majority of OCPI implementations do not switch the tariff during an ongoing session
2. OCPI does not define how to do this, it can be done either way without violating any requirements
3. It is OK to change the tariff during a session, causing a driver to get an unexpected cost

I feel like this might not be what the text was intended to convey. Either way, it should be clarified what is meant here - it feels like it's arguing against itself. 

Can someone please explain what the purpose of this section is?

**Comment by RobertdeLeeuw-IHomer** [comment]
OCPI is just the protocol used to communicate tariffs. In most countries, there are consumer laws that will prohibit changing a tariff after a consumer has accepted the therms and conditions (thus the tariff). 

Maybe we should rephrase this note a bit. Maybe add something about local legislation...

**Comment by RobertDeLeeuw** [comment]
What is required by local legislation for accepting terms and conditions varies. OCPI does not have any requirements for this, it only transports the data that might be needed. (Hopefully we have all the data needed in the protocol.)
OCPI 2.2.1 has "start_date_time" and "end_date_time" added, specificly for this use case.

See:  https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#131-tariff-object

**Comment by molacoste** [comment]
I see, is there a link for legislation in USA/Canada for this? 

And yes, from my understanding "start_date_time" and "end_date_time" can be applied, but it'll be on the whole tariff object. Does this mean that I could send a new tariff to a station with "start_date_time" of December 1st, and the station will keep its current tariff until that date when it will automatically update to the new one? Would I have to resend the current tariff beforehand adding the "end_date_time"?

I was trying to do the same thing using restrictions in PriceComponents since I'm using OCPI 2.1.1, but with "start_date_time" and "end_date_time" in OCPI 2.2.1, it looks like this works way better.

Thanks for the quick reply by the way!

**Comment by molacoste** [comment]
All good :) Ok yeah makes sense!
Cool, thanks Robert.

**Comment by RobertDeLeeuw** [comment]
Your welcome

@reinierl maybe something to improve a bit in a next version.
