### ISSUE TITLE
Sending CDRs #2

### ISSUE THREAD

**Issue by sc479** [ocpi/ocpi#331]
I repost this, because this question has not been answered yet. An example would be really instructive in this case.

"https://github.com/ocpi/ocpi/issues/287

2.) Within the response of a POST CDR there should be a Location parameter, but what means "The response should contain...". Are you talking about the well-known HTTP Location header, a JSON property within the general OCPI response header or even of an additional parameter within the CDR object which could be returned. Is the CDR anyway returned within the OCPI data property or is this empty? There seem to be no really complete specification about the POST response."

**Comment by RobertdeLeeuw-IHomer** [comment]
The sentence: "The response should contain..." Is in the section with title: "Response Headers". So it should be a response header.
I think the title in the table should be improved by changing it to: "HTTP Headers" instead of "Parameter"

BTW, thank you for making it 3 questions, that makes tracking changes etc a lot easier. I had asked the person that had posted this original question to split it into 3 questions, but I guess he never found time to do this.

**Comment by sc479** [comment]
Thank you for your answer!
