### ISSUE TITLE
EDL_40_SIG - signed data to small

### ISSUE THREAD

**Issue by martinschuberts** [ocpi/ocpi#344]
We have a question regarding the defined length of the signed_data field CiString(512).

An example EDL_40_SIG (see SAFE Software) value would not fit in this field (see example below)

We tried alternatively to extract the values and map to the corresponding fields - but there is no place for `meterValueSignature`.

How do you propose the handling of this values? Why is the `signed_data` field restricted to length of 512 characters?

Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<signedMeterValue>
    <publicKey encoding="base64">
        NF3VuHn8nBrwR19pyM2PwJ2rIHJi37htbEjsbuNsqohWKs1xy2LvQYa60ZqhcrKP
    </publicKey>
    <meterValueSignature encoding="base64">
        3mc6TTwTaYTKEc1xXPhxTFdJqh5U/vvwMPF5bxyEtSOtAxYIFNH7/TN4FjPM3fgJAII=
    </meterValueSignature>
    <signatureMethod>
        ECDSA192SHA256
    </signatureMethod>
    <encodingMethod>
        EDL
    </encodingMethod>
    <encodedMeterValue encoding="base64">
        CQFFTUgAAIjco2jOtWAIa6LYAsUAAAABAAERAP8e/3RsWAAAAAAAAIIEjCq6MECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGjOtWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    </encodedMeterValue>
</signedMeterValue>
```

**Comment by RobertdeLeeuw-IHomer** [comment]
@martinschuberts good point. OCPI signed data was developed without the support of parties that were developing the different solutions. All required the OCPI community to sign an exclusive agreement, which would result in their solution as only option in OCPI. Which we don't want to do, we dont want to only support one solutions when there are a number of possible solutions. 

Because of this we used the knowledge of OCPP as a base, as OCPP 2.0 had 512, we followed. OCPP had to release 2.0.1 to fix tis. OCPI has not yet released a fix for this. I will discuss with the development group how to solve this.

**Comment by ahzf** [comment]
Well, we (chargeIT and GraphDefined) never asked you to sign anything. We even accepted the initial OCPI CLA... but we will also not pay any money and do closed work just for some "bigger" fields in OCPI.

If you want to learn something about the only real Open Source solution for the German calibration law you can look at https://github.com/OpenChargingCloud/ChargyDesktopApp it is all Open Source.

**Comment by RobertdeLeeuw-IHomer** [comment]
@martinschuberts we have decided to release OCPI 2.2.1 to fix this issue. 
We plan to increase the length of `signed_data` to 5000, as this is machine-to-machine we dont see why we should have a narrow limit.
Question to you. Is the 512 length for `plain_data` large enough?
