### ISSUE TITLE
Example location contains incorrect field names

### ISSUE THREAD

**Issue by thanaParis** [ocpi/ocpi#346]
https://github.com/ocpi/ocpi/blob/master/examples/location_example.json

Connectors here use 'voltage' and 'amperage' where they should use 'max_voltage' and 'max_amperage' [according to the specification.](https://github.com/ocpi/ocpi/blob/master/mod_locations.asciidoc#133-connector-object)

**Comment by RobertdeLeeuw-IHomer** [comment]
@thanaParis thank you for reporting.
This is a known issue, lready fixed in the bugfix branch: https://github.com/ocpi/ocpi/tree/release-2.2-bugfixes
https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/examples/location_example.json

We hope to release a new documentation version soon, then we will merge these fixes to the master branch.
