### ISSUE TITLE
RESERVE_NOW fields

### ISSUE THREAD

**Issue by thanaParis** [ocpi/ocpi#350]
It is my understanding that the Token object in the ReserveNow command is used to populated the IdTag field in the OCPP ReserveNow.req message. However, Token.contract_id is a CiString(36), and IdTag is a case insensitive string of max length 20. If contract_id was truncated, I think this would cause issues--is that accurate?

Also, I'm having difficulty understanding the use of the optional authorization_reference field for ReserveNow objects. The specification says `A successful reservation will result in a new Session object being created by the CPO` but the Sessions object description for the authorization_reference field says `When the eMSP provided an authorization_reference in either: real-time authorization or StartSession, this field SHALL contain the same value` -- no mention of ReserveNow, and there's even a note `Different authorization_reference values might happen when for example a ReserveNow had a different authorization_reference then the value returned by a real-time authorization` which seems to imply that real-time authorization is supposed to occur when creating a Session on account of a reservation--but if that's the case, why is the field able to be provided in ReserveNow at all?

**Comment by RobertdeLeeuw-IHomer** [comment]
For the reservation, the Token.uid should be used, not the contract_id. Both are CiString(36).
But in OCPP it is identifierString(36). So that should work.

Looking at OCPP 1.6: that only support RFID as Token. In such case, only the RFID Token Type can be used. In such cases, the Token.uid will not be long as it is the hidden ID of the RFID. It might be useful to add a remark to explain that using other types for reservation to an OCPP 1.6 charge point might not work. 

Sharp of noticing that ReserveNow is missing in the text of the authorization_reference field in Session and CDR.
