### ISSUE TITLE
Switching Tariffs Example

### ISSUE THREAD

**Issue by langiole** [ocpi/ocpi#354]
The Tariff module contains an example of switching to a different tariff element found [here](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#example-switching-to-different-tariff-element-2), which reads as:

> Example Tariff to explain the step_size when switching from one TariffElement to another:
> 
> - Charging fee of 1.20 euro per hour (excl. VAT) before 17:00 with a step_size of 30 minutes (1800 seconds)
> - Charging fee of 2.40 euro per hour (excl. VAT) after 17:00 with a step_size of 15 minutes (900 seconds)
> - Parking fee of 1.00 euro per hour (excl. VAT) before 20:00 with a step_size of 15 minutes (900 seconds)
> 
> Example: switching to different Tariff Element #2
> 
> An EV driver plugs in at 16:35 and charges for 35 minutes (TIME). After that they immediately unplug, leaving with a total > session time of 35 minutes and a bill over the following costs:
> 
> - 25 billable minutes of charging time before 17:00, generating costs of 0.50 euro.
> - 20 billable minutes of charging time after 17:00, generating costs of 0.80 euro. As the Price Component of the last Tariff Element being used has a step_size of 15 minutes, the total duration is rounded to up to 45 minutes. When considering the already billed 25 minutes of charging time before 17:00, we are left with 20 minutes to bill after 17:00.
> - The total for this charging session is therefore 1.30 euro (excl. VAT).

I am not sure if I understand the explanation given for the second cost where it says 20 minutes of billable minutes of charging after 17:00 generates a total cost of 0.80 euro. My two concerns here:
1. If it was stated that the total charging time is 35 minutes and that 15 of those minutes where after 17:00, how is it that we have 20 billable minutes after 17:00?
2. If the step size is 15 minutes and we claim to have 20 billable minutes, then why aren't we billing for 30 minutes?

**Comment by mbayings** [comment]
You are right it looks strange and is complex. It has to do with that stepsize. When you start at 16.35, after 30 minutes you have had 2 steps and 3rd one begins. At that moment it is 17.05. Then a new step starts of 15 minuts which makes it up to 17.20.
If you would bill for only 30 minutes you miss the last 5 minutes of charging. That is the explanation but I agree it is much to complex with those stepsizes and we are thinking for OCPI v3.0 to simplify it one way or the other.

**Comment by thanaParis** [comment]
I am fairly sure there is a typo here.

> An EV driver plugs in at 16:35 and charges for 35 minutes (TIME). After that they immediately unplug, leaving with a total session time of 35 minutes and a bill over the following costs:

A charging session starting at 16:35 and lasting for 35 minutes would end at 17:10. However, the example says:

> 20 billable minutes of charging time after 17:00, generating costs of 0.80 euro. As the Price Component of the last Tariff Element being used has a step_size of 15 minutes, the total duration is rounded to up to 45 minutes. When considering the already billed 25 minutes of charging time before 17:00, we are left with 20 minutes to bill after 17:00.

This is incorrect. There are 10 billable minutes of charging time after 17:00. The total duration would be rounded up to 40 minutes, because there are 10 minutes of time billed to an element with a step_size of 15 minutes. The cost generated would be 0.60 euro.

This example rounds off the first charge:

> 25 billable minutes of charging time before 17:00, generating costs of 0.50 euro.

The first tariff element charges 1.20/hr, with a step_size of 30 minutes; starting at 16:35 with 25 billable minutes it should charge a full 0.60 euro due to the step_size. However it has a restriction--it stops applying at 17:00. Therefore it only charges 0.50 euro before the second tariff element takes over.

I think this example meant to be 45 minutes long, but it is still wrong there. A 45 minute session would end at 17:20, leaving 20 minutes after 17:00 for the second tariff to apply. However, with a step_size of 15 minutes, this would mean the second tariff applied twice, for a total charge of 1.20 euro, and the final price would be 1.70 euro.

**Comment by Alan-Stewart** [comment]
Tariffs can be ridiculously complicated.  And apparently what 2.2 defines is not enough because there are companies that want tariffs that just cannot be represented with the current data structures.  I think that in order to fully explain the complicated tariffs (and to reduce mistakes and confusion) we need to come up with a diagram to show how the tariffs map to the time spent.
`Arrive-----Start-----Change-----Finish-----Stop`
`16:35------16:35-----17:00------17:10------17:10`
`TIME=25m+0z@1.20 --- =10m+5z@2.40`
`---- 0.50 ----------- 0.60`
So the reasonable assumption would be a total cost of 1.10 but if the step-size is applied to the WHOLE time period instead of just the portion that's being billed, then 35m rounds up to 45m and so we have 10m+10z@2.40=0.80 for a total cost of 1.30.

The issue for me is that step-size is applied inconsistently.  Sometimes it's applied to a tariff element, sometimes it's not (when TIME is treated as a whole thing, not broken up into elements), and in this case it's applying to the whole TIME period, even though the Tariff being billed is just a portion of the TIME period.  This is way more complicated than it should be.

I honestly believe that if there is a step-size then it applies ONLY to the tariff element being calculated.  I do understand that there may be some TIME periods where double billing can overlap, but so what?  If the TIME charge is X for every N minutes spent charging (or portion thereof) and the PARKING charge is Y for every M minutes spent parked (or portion thereof) then I expect to be charged those two separate amounts.  It's simple, it's easy to calculate, and most importantly, it's easy to explain.  If the smartest engineers implementing OCPI cannot understand tariffs and step-size, how do we expect EV drivers to understand their bills?  As always, Keep-It-Simple.

**Comment by thanaParis** [comment]
> So the reasonable assumption would be a total cost of 1.10 but if the step-size is applied to the WHOLE time period instead of just the portion that's being billed, then 35m rounds up to 45m and so we have 10m+10z@2.40=0.80 for a total cost of 1.30.

I was wondering how they got 1.30 instead of 1.10; this is a clean explanation, thank you! ...I agree wholeheartedly that the step_size should apply only to the tariff element. Applying it like this to the whole time period makes very little sense to me, but at least now I see how they're doing it.

**Comment by Alan-Stewart** [comment]
To be fair, they do mention it:
> 20 billable minutes of charging time after 17:00, generating costs of 0.80 euro. As the Price Component of the last Tariff Element being used has a step_size of 15 minutes, the total duration is rounded to up to 45 minutes. When considering the already billed 25 minutes of charging time before 17:00, we are left with 20 minutes to bill after 17:00.

But it is still very confusing.  What they don't mention is WHY they are calculating it this way, and not the way that most people would assume would be how it was being done.

**Comment by mbayings** [comment]
We fully agree it is needless complex and in the new versions we do our best to explain it better. But more important we want to offer also a much more simplified tariff module. The current tariff model was created and based on input from the OCPI community, and we tried to make all requests possible. Result is a needless complex module. And as Alan says: keep it simple and set a structure that also the EV driver will understand. If you can't explain it easily, the EV driver will for sure not understand it. Taking into account consumer laws you must offer clear transparent and understandable tariffs to your customers.
