### ISSUE TITLE
OCPI Workshop #13

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#38]
_To be extended by Christina_
# Documentation Structure:

We developed the following new document structure to describe the protocol in a more consistent way:
- Chapter **Protocol Meta Information**, describes the connections between the parties
  - Section **Transport and Format**, current file _protocol.md_
  - Section **Status codes**, current file _status_codes.md_
  - Section **Version information endpoints**, current file _versions.md_
- Capter **Overview of Business Objects**, explaining the global picture with relations between objects
  - One section in one file per Object with the following structure:
    - Object Description
    - Inheritances
    - Flow and Lifecycle
    - Interfaces and endpoints
    - Object description
    - Data types
- Capter **Generic Types**, describing all data types that are used by multiple objects

**Comment by cristinarc** [comment]
## Regarding the CDRs

There’s some information that is going to be different for the live information about the session and the final CDR information. The way we can keep it separate is using a CDRInfoType object in the JSON for the ’Session’ and the ‘CDR’.

## Data structure updates
### Session
```
{
     info: {CDRInfoType},
     status: Enum value with few statuses,
     endpoints: {...}
}
```

### CDR
```
{
     info: {CDRInfoType},
     status: Enum value with few statuses (diff to the ones that are used for the session),
     endpoints: {...},
     sessionId: Needed to link to the session in case the eMPS wants to do so
}
```

Being the CDRInfoType 

```
{
	id: , 
	start_datetime: , 
	end_datetime: , 
	kWh: , 
	auth_id: , 
	location (object): ,
	evse (object): , 
	connector (object): , 
	meter_id (optional): , 
	currency: , 
	charging_periods (optional): ,
	total_cost: 
}
```

#### CPO will send this request to update the ongoing session:

```PUT session/{id}```

#### CPO will send this request to the eMSP to ‘close’ the session:

```DELETE session/{id}```

     
After that the endpoint can not be used any more. And if your session is not finished in your system you can update it to “finished”.

#### eMSP will call to CPO to this endpoint

```     GET XXX/cdr  ```

- With filters or to the URI of the CDR XXX/cdr/{id} that is sent in the information of the CDR —> Pagination and filters are super needed for this, otherwise you will get all the CDRs


#### CPO will send to the eMPS the CDR through this endpoint

```POST XXX/cdr```


The last status that should be sent for a session should be the _“finished”_ status. But when the eMSP is really _free_ to delete the endpoint for a specific session, is when the DELETE request has been received.
Note that the reason why you don’t expect the CDR in order to close the endpoint is because could be that a session is finished but the CDR is sent later for some reason (CPO needs to do some manual work e.g.).

Make clear in the document that the session will consider as ended by the CPO when the user is de-authorized.

There will be an **authentication** process through and an authentication_id is generated by the eMSP and sent to the CPO. This is required so it can be used in the session information and the CDR information.
There is a next step through which the CPO POSTs to the eMSP information about the related session, with status _"active"_ (initial idea was pending), to which  the eMSP can react informing about the acceptance of the session or the confusion with the sent data. The CPO could start the session already if trusts enough its system, since the "authentication_id" has been already generated by the eMSP.

The idea is that the time between the authentication and the POST about the session there’s almost not time in between. After that the CPO can consider the session as “active”.

#### Posible statuses per object

Enum for Session: ACTIVE, FINISHED
Enum for the CDR: VALID, INVALID, DISPUTED

If any of the requests that have been sent to the eMSP are wrong, e.g because the authentication_id in unknown, a response will be sent with an error: "the invalid parameter”.

### Structure of the documentation (take previous note into account)
Hierarchical structure will be used for the objects. E.g. CPO Session object & eMSP Session object should be defined separately. Then is easier to write a Diagram and interaction in the definitions of the whole communication and the processes around it.

How to deal with the object should explained separately of the detailed description of the object. The object naming should be descriptive themselves so it can detailed somewhere else with no problems (they could be just used for implementation of deep and technical discussions).

### Next workshop
- Filter & pagination
- When having someone that can take care of documentation, do the session for documentation. Really important doing that ASAP.
- Advance tariffs structure will be done according to the parties that are present in the meeting and will try to make it easily extensible for the other parties that could have other needs.

**Comment by simonphilips** [comment]
Photograph describing the session/CDR flow. Also includes the explicitly split session and CDR objects with a common field.

![img_20150904_130305](https://cloud.githubusercontent.com/assets/3263809/9712781/60fae800-554d-11e5-8a4a-2ff0786b47f4.jpg)

Small remark: I think the id should be removed from the CDRInfo and into the session/CDR object itself as this id has a different meaning (i.e. points to a different type object).
