### ISSUE TITLE
Which step_size do we consider when we have two price_components in the tariff_Element ?

### ISSUE THREAD

**Issue by anasquazbary** [ocpi/ocpi#386]
Hello !
I have a question concerning step_size in a specific case :
The EV charges 3 minutes then spend 6 minutes on parking
Here is the tariff : (only 1 TariffElement with no restrictions)

```
{
	"elements": [
		{
			"price_components": [
				{
					"type": "TIME",
					"price": 1,
					"step_size": 300 //5 minutes
				},
				{
					"type": "PARKING_TIME",
					"price": 2,
					"step_size": 420 //7 minutes
				}
			]
		}
	]
}
```

For me, one charging period is enought, I’m I correct ?

Since we have two step_size, I am wondering if we should for example choose the more advantageous step_size for the user (the one that gives the lowest cost)? Or is there a rule that says that we always consider the TIME step_size take over on the PARKING_TIME (or the opposite) ? Or another rule ?

So, which step_size should we consider and how do we calculate the final cost ?

Thank you for reading !

**Comment by SoloVeniaASaludar** [comment]
I think there are in the specification an example that matches the case you describe. On it you can read:

"As the tariff switches from a TIME based tariff to PARKING_TIME, step_size is not used on the charging time, only on the parking time"

In conclusion, in your example, EV must pay for 3 minutes of charging (no step size applies) and 7 minutes of parking.

About the number of charging periods, in order to create a CDR who describes all the charging aspects of session you will need two. It is the only way to say there are an initial TIME of 3 minutes followed of a PARKING of 6 minutes,

**Comment by anasquazbary** [comment]
Thank you for your quick response ! 
I think this example is similar to the one in [this comment](https://github.com/ocpi/ocpi/issues/289#issuecomment-730226750) .
If we apply the same rule, it should be 3 minute for TIME and 5 + (14-9) = 10 minutes for PARKING_TIME.
Is there a difference between my example and the one in the comment ?

**Comment by mbayings** [comment]
My advise: don't mix parking and charging at all. We see a lot of issues when these are mixed and it makes it also almost totally not understandable and transparent for the EV driver. If you want to use parking time, I would create a totally separate session and CDR for it. 
We put it in OCPI, on request of CPOs and MSPs but the usage and implementation always creates issues.

**Comment by anasquazbary** [comment]
Thank you for your answers, with 2 charging periods the rule **"Only the last ChargingPeriod that is relevant for
calculating TIME or PARKING_TIME based cost shall take into account the step_size"** implies indeed that we only apply step size for the second charging period (so for the parking).
