### ISSUE TITLE
Price rounding

### ISSUE THREAD

**Issue by kYann** [ocpi/ocpi#401]
Hello,

When rounding a number, there is different way of rounding it (banking rounding, closer to zero, away from zero, etc).
After calculating a charge price, we need to round the price so we don't endup with 10 decimal digits.
What is the correct rounding method ?

We also need to know if we do the rounding on the final value or if we do the rounding for each result of a tariff element.

Thanks,

**Comment by reinierl** [comment]
Sorry that I left this issue alone for so long.  I don't think OCPI mandates one way of rounding or the other, as you noticed.

That would mean that the session fee may be slightly different when computed based on the same data by different parties due to rouding differences.

The same with rounding results per component or only the sum of all the prices of all components: it's up to you.

For OCPI 3.0 we made an explicit Business Use Case that MSPs will want to recompute the session fees computed by CPOs in order to check them. So hopefully things will be better there, even though we haven't really fleshed out a method to achieve this goal yet.

**Comment by reinierl** [comment]
Based on a discussion in the last OCPI Development Working Group call on 2022-08-18 we added a note to the Tariffs module about this: https://github.com/ocpi/ocpi/commit/b735ff06d11d11e3cb61dc6deb3fccd0a3dda2a5
