### ISSUE TITLE
The meaning of a price_component with no vat

### ISSUE THREAD

**Issue by anasquazbary** [ocpi/ocpi#409]
Hello ! 

I am wondering what is the meaning of a price_component with no vat. When no vat is given in a price_component that is used, the total cost will have a field `incl_vat = null`. In this case, what do the customer pay ? Does it mean that he only pays the cost without a vat?

Thank you for reading :)

**Comment by reinierl** [comment]
The specification says about the `vat` field:

> If omitted, no VAT is applicable.

That would mean that the customer pays the price excluding VAT and no value added tax is paid over this component of the price.

Now of course OCPI is just a tool and you are always required to follow the law. If you suspect that the VAT information that a CPO is sending you is not correct, ask them to fix it, or use the correct information according to the law instead of what they send.

**Comment by anasquazbary** [comment]
Thank you @reinierl ! =)
