### ISSUE TITLE
Tariff calculations questions

### ISSUE THREAD

**Issue by sssmolarkiewicz** [ocpi/ocpi#424]
Hello!
I have some questions considering multiple aspects of tariff calculations, that I would like to clarify.

### Rounding with step size
After a lot of reading the spec and github issues, I think I have an idea of how step size works except one thing. The spec contains an example:
![Zrzut ekranu z 2023-02-20 15-46-03](https://user-images.githubusercontent.com/100124335/220137493-d13ce2af-3483-4273-aa1b-da7877e6ba15.png)
My concern is about `When considering the already billed 25 minutes of charging time before 17:00...` - what if the 25 minutes of charging wasn't yet billed? Consider the tariff:
```json
{
  "elements": [
    {
      "restrictions": {
        "start_time": "00:00",
        "end_time": "17:00"
      },
      "price_components": {
        "type": "FLAT",
        "price": 10
      }
    },
    {
      "restrictions": {
        "start_time": "17:00",
        "end_time": "00:00"
      },
      "price_components": {
        "type": "TIME",
        "price": 1,
        "step_size": 900
      }
    }
  ]
}
```
and the same charging session as in the example in the docs. So the session time is still 35 minutes, of which 10 minutes was charging after 17:00, but the tariff element until 17:00 has only a FLAT component. How should the session time be billed? I round up the total session time to 45min according to the last TIME charging period, and a) add the difference (45-35=10) to the last charging period and bill 20 minutes (10+10=20), or b) bill whole 45 minutes according to the last price component, as no session time was yet billed?

### Multiple tariffs applicable
Consider the session to which multiple tariffs are applicable (either because of tariff type (charging preferences) or start/end dates). The docs state:
![Zrzut ekranu z 2023-02-20 16-00-40](https://user-images.githubusercontent.com/100124335/220140730-f5ea8e36-ba1c-48bd-a443-b90c927ed86f.png)
Am I understanding correctly, that if I have charging periods: [0,10) with ENERGY dimension billed with Tariff1, and [10, 20) with TIME dimension billed with Tariff2, I should only apply TIME step size from Tariff2 (as after the first charging period the tariff was switched, so I don't take the step size into account)?

### Can charging periods overlap?
There is no infromation in the spec, so I assume that if it's not forbidden it's permitted. Does it make any difference if I create one charging period with multiple dimensions, or multiple charging periods one dimension each (possibly multiple charging periods would cover the same time interval)?

### Can FLAT fee of one tariff element be applied multiple times?
Bumping the question not answered in [this issue](https://github.com/ocpi/ocpi/issues/390), if I have a tariff
```json
"elements": [{
  "price_components": [{
    "type": "FLAT",
    "price": 1.00,
    "step_size": 1
}],
  "restrictions": {
    "max_power": 1 
  }
}]
```
and a session:
- The first 10 minutes, the power is equal to 0.5 kW
- From minute 10 to minute 20, the power is equal to 2 kW
- From minute 20 to minute 30, the power is equal to 0.5 kW

Is the price for this session 2 (as the tariff element is active in two charging periods), or 1 (as this is a FLAT fee and can only apply once)?

**Comment by reinierl** [comment]
> How should the session time be billed? I round up the total session time to 45min according to the last TIME charging period, and a) add the difference (45-35=10) to the last charging period and bill 20 minutes (10+10=20), or b) bill whole 45 minutes according to the last price component, as no session time was yet billed?

The former. You bill the flat fee for what happened before 17:00 and you bill 20 minutes of charging time at 1 currency unit per hour.

> Am I understanding correctly, that if I have charging periods: [0,10) with ENERGY dimension billed with Tariff1, and [10, 20) with TIME dimension billed with Tariff2, I should only apply TIME step size from Tariff2 (as after the first charging period the tariff was switched, so I don't take the step size into account)?

Yes, you understand this correctly. Using multiple Tariffs for one Session is awkward though. OCPI 2.1.1 and 2.2.1 allow it but in the OCPI Development Working Group we consider this a mistake. It will not be possible in OCPI 3.0.

> Can charging periods overlap?

No. It's actually impossible because charging periods only contain a start timestamp. The start timestamp of one period is also the implicit stop timestamp of the period before that. So there is no way to even express overlapping charging periods in OCPI.

> Can FLAT fee of one tariff element be applied multiple times?

I doubt if this question was even considered during the design of the Tariff system. Because Price Components are applied in a certain charging period, I'd say 2 is the answer that would come out of a "simplest thing that could possibly work" algorithm that implements the spec.

Because that's probably not what was intended, perhaps the spec needs additional rules about FLAT price components.

**Comment by sssmolarkiewicz** [comment]
Thank you so much for your answer.

**Comment by reinierl** [comment]
@TylerNielsen I meant just "Tariffs" there. Multiple TariffElements in one Session is fine. But in OCPI 2.x there are two possibilities for making the price for energy change at 18:00 on Wednesdays. Either you can make a TariffElement with an appropriate restriction within one Tariff, or you set an altogether different Tariff on the same connector at 18:00 on every Wednesday.

Having two ways to do the same thing is just unnecessary complexity, and the way with different Tariffs is less transparent to MSPs and their Drivers. Therefore CPOs should use multiple TariffElements instead of different Tariffs wherever possible.

And yes, you'll have to know the Tariff to appropriately cut a Session into Charging Periods. It also makes that MSPs can't really check the way a CPO split the Session into Charging Periods - they don't have the Tariff-agnostic raw data that the CPO summarized into Charging Periods. I think ultimately this trust problem between CPO and MSP has to be solved using signed meter readings. A system like what is envisioned in the German Mess- und Eichrecht regulations. At the moment I have the impression that we're not there in the industry.
