### ISSUE TITLE
Clarification of "uniquely identifies"

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#427]
EVSE.uid, among other columns, is described as a string that "uniquely identifies the EVSE within the CPOs platform (and suboperator platforms)" and "this field can never be changed, modified, or renamed".  It turns out that I interpret this differently than a partner's OCPI implementation.  Which is the correct interpretation here:

1) One and only one EVSE with this uid can exist in a CPO's Location data: if it is physically removed and installed at a different Location, the EVSE is no longer listed at its original Location and appears in a new Location.

2) Multiple EVSEs with this uid can exist if all but one has a status REMOVED:  if it is physically removed and installed at a different Location, an EVSE with this uid remains at the original Location with status REMOVED, and an EVSE with the same uid appears at a new Location with a status that is not REMOVED.

I (and every other CPO I have worked with) have been interpreting it as case 1, because the phrase "uniquely identifies" is used with other entities such as Location id, Token contract_id, CdrLocation id, and so on.  In those cases it is strongly implied (but not explicitly said) that there is one and only one item of that class with that identifier.

But I can see use-case validity in case 2.  Should an OCPI implementation support both approaches?  Is one of these wholly unexpected and requires clarification in the specification?

**Comment by reinierl** [comment]
Hmm. Yes I see both use cases.

I think (1) is in line with the wording of the spec.

(2) makes more sense for a CPO operationally.

The spec says:

> When the CPO wants to delete an EVSE from the list of active EVSEs, they MUST update the EVSE’s status field to REMOVED and call the [PUT](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_locations.asciidoc#mod_locations_put_method) or [PATCH](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_locations.asciidoc#mod_locations_patch_method) on the eMSP system. A Location without any valid EVSE object can be considered expired and should no longer be displayed. There is no way to entirely delete Locations, EVSEs and Connectors (...).

But that would mean that if a charging station is physically removed from one Location and reinstalled at another, that station's EVSEs would have to appear at the other Location with different UIDs. They can't have the same UID because the old UID would still be attached to the EVSEs at the old Location that now have status `REMOVED`. And UIDs have to be unique within the CPO's platform as you quote.

I will put this on the list for discussion in the OCPI Development Working Group.

**Comment by julius-yang** [comment]
This issue is related to https://github.com/ocpi/ocpi/issues/412.

I would prefer approach 1 by explicitly stating that if an EVSE.uid exists in the data, it must be assigned to one and only one Location.   I prefer this approach because our OCPI implementation fundamentally rests on this idea, and every CPO but one -- out of three dozen we work with -- seems to have also interpreted it this way as well.

**Comment by Alan-Stewart** [comment]
I would agree with @julius-yang.  I see the OCPI standard as dealing with _virtual_ things.  Yes, most virtual objects are backed up by _real_ objects (kinda have to be), but the identifiers represent "pretend" things and are not attached to the "real" things.  If an EVSE with three connectors is moved from one location to another, it **must** be given a unique ID at the new Location because at that Location, it's a "brand new" EVSE.  Unless you were replacing an existing EVSE?  Then do you assign the old ID, use the previous EVSE ID, or make up a brand new one?  I'm not sure there.  If you were to remove the three cables from that EVSE and put them on a different EVSE at a new Location, would you expect to move those Connector IDs over?

**Comment by ahzf** [comment]
The exact semantical meaning of an EVSE Id in e-mobility is sadly very wage. OCPI tries to solve that, but in the end everything is worse than before. This "EVSE UId" concept of OCPI is clearly a bug pattern as it leaks internal information to the outside. I really do not want to know the dirtly details of your SQL database! ;)

As OCPI is roaming protocol an EVSE identification is clearly a place on a map where EV drivers can charge. It is NOT a unique identification of a charging station, nor of an electric circuit within a charging station. Please remember, that OCPI does not have a concept of charging stations, just EVSEs... which is clearly another bug pattern.

Whenever you do changes to a physical charging station, e.g. you move it on the map farer than just some meters or you replace the hardware you have to use a new EVSE Id. This is required because of the distributed async nature of EV roaming data. You never know when your data is updated in the databases of an EMP, thus there might be requests for EVSEs, that no longer exist within your CPO backend or changed. You have to avoid this.

EVSE Ids should be unique, this includes to be unique over time. Reusing identifications without a long grace period is a bug pattern.

For OCPI please do never use anything else than the official eMI3/15118 EVSE Ids like "DE*GEF*E123*456*1" for the EVSE UId. They had been defined this way to solve at least some of the common problems of distributed systems.

**Comment by ahzf** [comment]
@reinierl It is not realistic, that no one will delete EVSEs or Locations in OCPI. The `REMOVED` status must clearly be interpreted as a status for a grace period until everyone in the distributed roaming system is aware that those EVSEs and Locations are no longer existing and that this had been intentional.

But in the end this `REMOVED` status is just some status to be nice to each other. You still have to handle errors as errors always happen and you might update you Locations and EVSEs and find out, that some are no longer listed within the new data set. Now it would be smart to assume, that they had been removed and you set a `REMOVED` status for your own within your own database. After a grace period you will delete them.

Maybe you do not want to do that on the first dataset you process, because a missing EVSE or location might just be an error. So you might want to have an additional `MAYBE_REMOVED` status within your EMP database.

**Comment by julius-yang** [comment]
> For OCPI please do never use anything else than the official eMI3/15118 EVSE Ids like e.g. `DE*GEF*E123*456*1` for the EVSE UId. They had been defined this way to solve at least some of the common problems of distributed systems.

I assume you are asking this because the eMI3 identifier contains the CPO identifier itself and thus must be unique across all CPOs.  If that is the reason there are a few problems:

1) No backwards compatibility.  Many CPOs are using UUIDs for EVSE.uid already.
2) Companies sell chargers (or themselves!) to other companies.  If DE*ABC buys DE*DEF, then two strings DE*ABC *and* DE*DEF reference the same CPO, or all DE*DEF uids must change to DE*ABC uids, violating the immutability restriction.

This discussion belongs more properly in #412 however.

**Comment by julius-yang** [comment]
> I would agree with @julius-yang. I see the OCPI standard as dealing with _virtual_ things. Yes, most virtual objects are backed up by _real_ objects (kinda have to be), but the identifiers represent "pretend" things and are not attached to the "real" things.

As an eMSP, I agree with you.  If an OCPI EVSE were an abstract thing where replacing hardware didn't change the uid/physical_reference that would be paradise.

But having had a tiny bit of CPO experience I think this would be very painful for CPOs.  Charging equipment has a unique identifier which OCPP (and maybe firmware) use.  This identifier is attached to the hardware.  It also often becomes the EVSE uid -- if it doesn't then the CPO has to keep a separate association between internal id and uid, which is a LOT of bookkeeping for someone with thousands of EVSEs.   If the hardware is picked up and moved somewhere else, it is far easier for the CPO to leave the identifier alone and associate the EVSE with a new Location.

**Comment by ahzf** [comment]
EVSE Ids in OCPP are "1", "2" or 1, 2 depending on the OCPP version. That's all.
Charging stations (or charge points in older versions) are identified in multiple ways from IP addresses to digital certificates.

So there is always a mapping happening.

And when a charging station is moved or replaced, there is some configuration required anyway. So you can also update the EVSE Id mapping.

--------------------------------------------------------------------------------

Are you also unhappy, when your compiler tells you, that you code will not compile and then switch to a scripting language?
We are not discussing emotions here. Just verifyable facts.

**Comment by reinierl** [comment]
We're going to add the following note to the description of the `uid` field in the next documentation release of OCPI 2.2.1:

> Note that in order to fulfill both the requirement that an EVSE’s uid be unique within a CPO’s platform and the requirement that EVSEs are never deleted, a CPO will typically want to avoid using identifiers of the physical hardware for this uid property. If they do use such a physical identifier, they will find themselves breaking the uniqueness requirement for uid when the same physical EVSE is redeployed at another Location.

Something similar will be done in OCPI 3.0.

**Comment by julius-yang** [comment]
In my opinion the core problem is that "uniquely identifies" is not strongly and clearly defined.  The entry for EVSE.uid does not explicitly forbid multiple EVSEs with the same uid from existing in the data.

"Uniquely identifies the EVSE within the CPOs platform (and suboperator platforms).  For example a database ID..."

For example my credit card has a number that uniquely identifies it.  But if I am issued a new physical copy of that card with the same number, now I have two physical cards with that number.  Conceptually I still have only one credit card though.  So the number still uniquely identifies my credit card.

Here is my attempt at a strong and clear definition:

"A class attribute value that 'uniquely identifies' a class exists once and only once across all instances of that class."

By clearly defining "uniquely identifies" there is no need to bring up a particular use case.  That use case, along with every other crazy reason a CPO can invent to duplicate uids in their data, is forbidden.
