### ISSUE TITLE
OCPP Charging Station Identity Mapping to Location

### ISSUE THREAD

**Issue by gvasmatkar** [ocpi/ocpi#436]
Hi All,

This probably is an easy one but I am still confused.

How do I map the charging station identity (from OCPP J endpoint URL connection string) to the Location?

For example - **ws://csms.example.com/ocpp/CS001**

My understanding is **CS001** will be mapped to the Location object.

However, the exerpt from OCPP 2.0 spec says -

`The Charging Station identity datatype is identifierString (For definition see [OCPP2.0.1-PART2] Additionally the colon ":" character might not be used, because the unique identifier is also used for the basic authentication username. The colon ":" character is used to separate the basic authentication username and the password. The maximum length of the Charging Station identity is: 48 (Note: Maximum length was chosen to ensure compatibility with EVSE ID from [EMI3-BO] "Part 2: business objects.
`

What gets me confused is what has charging station identity to do with the EVSE ID ? Even if the a charging station has only a single EVSE, the charging station identity and EVSE ID will be two different things.

Best Regards,
Girish

**Comment by reinierl** [comment]
The Charging Station concept from OCPP is not in OCPI in any way.

Typically, CPOs use the OCPP charging station identity (so the **CS001** from your example) among other things to construct the value of the `uid` field of the EVSE objects in a Location in OCPI. But this is not a requirement of OCPI.

The OCPI Location object is agnostic of the notion of charging station because a driver looking to charge their vehicle, and their eMSP, are typically not interested in which OCPP connections the charging hardware have. They do care about these things:

 * Where in the world they can find charging facilities (the _Location_ object)
 * If these are currently available for charging (the _EVSE_ object)
 * And if these are compatible with their vehicle (the _Connector_ object)

We talked about adding the Charging Station concept to OCPI 3.0 but there is no compelling use case for it so far. Also there are definition problems: would a Charging Station in OCPI be defined as the thing that has one OCPP connection (as OCPP does), or the thing that has one authentication user interface (as EMI3 does), or the thing that is somehow humanly identifiable as a separate enclosure (the common-sense meaning of the term charging station)?
