### ISSUE TITLE
Offset +00:00 in DateTime

### ISSUE THREAD

**Issue by yukinarit** [ocpi/ocpi#464]
Hi Thank you for maintaining the repo!

I have a question regarding DateTime in OCPI. In the  [**1.2. DateTime type**](https://github.com/ocpi/ocpi/blob/master/types.asciidoc#12-datetime-type)

 it says

> +00:00 is not the same as UTC.

But as far as I understand `+00:00` is the same as `Z` and UTC in the context of RFC 3339? Could somebody explain what it means and why it is not the same? :thinking: 

Also, is `2018-01-01T01:08:01.123+00:00` allowed in OCPI?

**Comment by reinierl** [comment]
Hi @yukinarit . I had the same question when reading OCPI 2.2.1's definition of datetime. So for OCPI 3.0 I rewrote it to:

```
All timestamps SHALL be formatted as string following RFC 3339, with the following additional limitations:
• All timestamps SHALL be in UTC.
• Fractional seconds MAY be used.
• When fractional seconds are given, there SHALL be either one or three decimals after the point.
These are examples of valid values for DateTime fields:
   2015-06-29T20:39:09Z
   2016-12-29T17:45:09.2Z
   2018-01-01T01:08:01.123Z
```

For OCPI 2.1.1 and 2.2.1, I think the safest bet is to always use "Z" as a timezone specifier. The intention of the old wording may have been to make people use "Z" instead of "+00:00".

**Comment by yukinarit** [comment]
Hi @reinierl 
Thank you for the prompt reply!
It's clear to me now.
