### ISSUE TITLE
Relevant EVSE and connector in session location

### ISSUE THREAD

**Issue by basilfx** [ocpi/ocpi#469]
We receive many session via OCPI 2.1.1 from CPOs that either include too many EVSEs or none, as part of the location details. We need that information for many other purposes (especially validation), and crap in is often crap out. We rather inform the CPO that they sent an invalid request.

OCPI 2.1.1d2 section 9.3.1 has the following description for the `location` property of a `Session` object: "the location where this session took place, including only the relevant EVSE and connector".

Our problem is the word 'relevant': it is open to interpretation and does not necessarily mean 'only the one EVSE and connector where the session is physically connected with (or will be connected with in case of a reservation)'. Because Location has cardinality 1, but the EVSE in Location has cardinality *, things become even more open to interpretation.

Similar issues (#286 and #149) have been opened to discuss the same problem w.r.t. CDRs. @RobertDeLeeuw stated the following in them:

- "To be able to charge at a location, there needs to be an EVSE, so the EVSE Id can be required in the CdrLocation object."
- "Yes, we are indeed not enforcing this via the object definition. The idea was to send the full object, and limit it by what is written in the specification."

In line of the above logic, I would define relevant as only the EVSE and connector where the session is physically connected with. Nothing more, nothing less. That is probably in line with the intention.

To address this issue, we'd like to know how to interpret this.

**Comment by reinierl** [comment]
Indeed. I believe that the intention is to send the EVSE that was occupied in the Session and the Connector that was used in the Session. So there should be one EVSE in the Location, and one Connector in the EVSE, in this case.

The wording is unnecessarily fuzzy but I don't think we'll work on 2.1.1 anymore. 

I see that the current 3.0 draft, probably taking it straight from the 2.2.1 spec, retains the "relevant" wording but has a specific CdrLocation object with fields with cardinality 1 for the EVSE ID and Connector ID. So that's another indication that the intention is to identify exactly one in Connector.

**Comment by basilfx** [comment]
Thank you for confirming this. 

I fully understand no work is put in 2.1.1 anymore, but this helps. OCPI 2.1.1 is still used by a majority of our partners, and it would not be the first discussion about the exact interpretation ;-)

I'll close the issue.
