### ISSUE TITLE
Check endpoint structure consistency

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#49]
Through the documentation the endpoints don't have a homogeneous structure, some are `/<path>/<role>/<version>/<class>/<object>` and some `/<path>/<role>/<class>/<object>`.

Maybe the structure could be described in one section, including the definition for the different segments like `<path>`.

**Comment by poohsen** [comment]
it's important to bear in mind that those endpoint paths are just examples. They really could be anything for any given implementing party.

So there isn't really a structure to describe. But it would be better to be consistent in the examples. Do you have examples of the /<path>/<role>/<class>/<object> case? (the "version information endpoint" is special because it's meant to be the same for all versions and so doesn't include a version in the path)

**Comment by simonschllng** [comment]
Ok, then your sentence 

should be added to the documentation. Preferable in the beginning as it is valid for all endpoint examples. Furthermore we should mark the endpoints and everything that is an example. This would make it more clear.

*Additional Question:* Is it important to have the version number in the endpoint URL? Shouldn't it at least be an advice to do so?

*Examples for different endpoints are:*
[bo_sessions.md#31-operator-interface](https://github.com/ocpi/ocpi/blob/master/bo_sessions.md#31-operator-interface), which was originally written as: *PATCH to /sessions/{id}* in 53fde827 sessions.md:84. There are more examples originating from the same commit.
Or do some endpoints differ on purpose?

**Comment by poohsen** [comment]
> Ok, then your sentence ... should be added to the documentation

agree.

> Is it important to have the version number in the endpoint URL? Shouldn't it at least be an advice to do so?

well, it's technically not necessary but we might still want to add an advice because it makes it explicit and thus easier to work with
