### ISSUE TITLE
How the CPO should correct an already sent CDR?

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#55]
This subject was discussed during the face to face meeting we had on Friday and I could not reach a clear conclusion on that matter. But mainly, we decided that the CPO could send a DELETE http request to **invalidate** an already sent CDR and, afterwards, they could send the correct CDR.

The problem of that solution is that, there is not link between the **invalidated** and **correct** CDR, meaning that it makes really difficult for the eMSP to represent this information in a comprehensible way for the customer (e.g. it was already billed).

The idea we concluded at TNM and we think would make this correction less error prompt and faster, is doing both steps at the time.

Add field **corrected_cdr_id**: The CDR would contain this new field that would indicate if the CDR is a corrective CDR or not, pointing as well what is the CDR that it would be correcting. This field would be optional, so it would just be used for these special cases. The name we proposed is based on our experience and systems.

This solution would also cover those strange cases for which there is not a CDR that corrects the invalidated one, the values should just be 0. Meaning that the DELETE command would not be allowed any more, since it could be really easily miss-used to invalidate first and then create another one (as is described in the 1st paragraph).

**Note**: 
The response to this can be success or failure. In our case it will just depend on the format of the CDR and its fields. In order to make our system capable to validate 100% that is possible to process the CDR, is needed that an asynchronous failure can be reported to the CPO. As discussed in the core group, it will be taken into consideration for a later release.

**Comment by simonschllng** [comment]
Would an alternative solution also work, where _every_ CDR references a session ID? That way you can clearly identify the session and quickly find all CDRs for one session, of which only one should be in a _non-deleted_-state.

**Comment by cristinarc** [comment]
The only problem about it is that you rely on the moment you have received the CDR, it would be the only way to know which one is the correct one and which one is correcting the other/s.

On the other hand, if what you mean is that it would be done after the DELETE request I proposed we get rid of, the 2 steps would still exist. Which is not a bad solution neither but we opt better for one the step solution, which is optimized for the most common case: a CDR corrects other instead of the least common case: a CDR was sent by mistake.

**Comment by poohsen** [comment]
the atomic POST of a CDR which references another CDR that it's supposed to correct is more suited for systems architectures that use queues. We have such an architecture at TNM. The system handling settlement on the basis of CDRs is consuming CDRs off a queue and is not connected to the outside world.

If we were to handle separate DELETE and POST events in the OCPI-MSP application, we'd need to keep track of what CDRs we accepted in the past so that we could interpret DELETE messages correctly. If all we ever get are POSTs, we can pass them on to the queue more or less directly. This simplifies the OCPI-MSP application.

This is one advantage of the approach that Cristina advocates. I think this is a complex issue and I'd like to hear other implementers' opinions on this.

**Comment by fedragon** [comment]
Has this issue been discussed any further? This is still quite relevant for us at NewMotion ...

**Comment by RobertdeLeeuw-IHomer** [comment]
Hi Federico,

This issue is high on the list for OCPI 2.2

**Comment by fedragon** [comment]
I see, thank you!

**Comment by RobertdeLeeuw-IHomer** [comment]
Added the ability to send a Credit CDR
