### ISSUE TITLE
On-demand authorization of tokens

### ISSUE THREAD

**Issue by jarmotuisk** [ocpi/ocpi#57]
I strongly believe that the capability to check the validity of the token on on-demand/real-time basis would greatly improve the usability of OCPI protocol. It should not be made mandatory for CPO to keep tens of thousands tokens dormant on their system, just in case they are needed.

Of course keeping local whitelists helps to tackle potential communication breakdown related issues. So both approaches have its benefits. But in case on back-end to back-end integrations such breakdowns occur rarely.

**Comment by simonschllng** [comment]
This is already defined but not jet part of the documentation. It will be added very soon.

**Comment by rutgerplantenga** [comment]
'It should not be made mandatory for CPO to keep tens of thousands tokens dormant on their system, just in case they are needed' - Please note that this concept of disitributing a list/directory of all tokens to all CPO's is quite central to OCPI, even once on-demand authorisation is there. 

This is because of the decentral nature of OCPI and the need for any CPO to understand which MSP to ask for authorisation. Also, it should not be such a big deal as on CPO-side, right? It's really just a simple list of all tokens from all connected MSP's. 

Fully agree that on-demand authorisation adds a lot of value though, also because it puts much more authorisation-control on the MSP side (to e.g. authorise prepaid card sessions or to apply much more fine-grained authorisation decisions).

**Comment by jarmotuisk** [comment]
I see the point Rutger makes, distribution of whitelist is essential in most of the cases to initially define the MSP. If that is defined beforehand (with different methods) or for later checkup though on-demand would be helpful.

**Comment by simonphilips** [comment]
Most of the confusion comes from the "whitelist" name. It is not a whitelist but a reference list to identify the MSP for each token (otherwise you would have to spam every connected MSP to your platform). 

The typical flow would be:

1. Driver holds RFID card against the EVSE.
2. The CPO looks up the token in his reference list
3. The CPO contacts the eMSP that owns this token and verifies if this token can start a session.

However, we can extend this mechanism to let MSP's describe each token: for example if he allows a token to be whitelisted or not (this might be interesting for offline stations). That depends on the eMSP's businessmodel and the CPO's technical capabilities, but the functionality can be used if both parties enable it.

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed
