### ISSUE TITLE
Brand names for charging stations?

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#72]
Hi there,

as someone working with CPOs/EVSE operators there is more and more the case that a customer buys many charging stations which are all operated by us. But for marketing reasons every navigation service provider, map or app creator should not (only) show our logo, but the logo of the customer (together with a small "powered by..." perhaps).

Therefore I suggest a new field "brand", which is more or less like the BusinessDetails object and consists of:
- Id (something short)
- a multi-langue name (the legal name in the different countries)
- a link to the logo to be used by navigation service providers, map or app creators
- a link to the homepage [optional]

Perhaps this field might also be useful for an entire location, but I think it is not useful for a single EVSE. 

If think the Sub-Operator field is neither a good fit for this, nor really self-explanatory.

**Comment by mbayings** [comment]
Interesting suggestion. But I am not sure if this is the goal of OCPI. I understand the marketing reasons for this, but shouldn't this be part of the logo's from the operators for their cp's? They can make individual icons per station included the 'powered by'. Reason of my doubt is that OCPI should be as lean and mean as possible to support maximum implementations, containing the necessary functionality to support roaming, remote access, billing and info to the end user. 
However I can imagine that we have a differentiation in "owner" and "operator" as text, as that is usefull info for the EV Drivers, but that is supported by the Sub-Operator I think. 
But we can always put this request on the whish list for a new release.

**Comment by simonschllng** [comment]
Maybe we should simply extend the description for the sub-operator in [3.1 Location Object](https://github.com/ocpi/ocpi/blob/master/mod_locations.md#31-location-object), as it definitely is not intuitive.

**Comment by rutgerplantenga** [comment]
Indeed, I would be in favor of that solution as the sub-operator concept
was definitely aimed to include cases like these.

Rutger


*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam

**Comment by mbayings** [comment]
I agree with Rutger and Simon. @ahzf would that be OK for you?

**Comment by ahzf** [comment]
@mbayings At least OCPI should provide the brand name somewhere as text, as only this will allow an ev driver to search for it. 

As OCPI is a distributed protocol: What is the real meaning of the "suboperator" field in context of OCPI? I can understand that centralized protocols like Intercharge have s.th. like a "hub operator"-field, as being attached to Hubject costs money and sharing this between multiple makes sense (even this field name is not really a good choice). But when we are freely on the Internet this is no longer the case. So why should one operator be "behind" another one? If you want to share hardware resources and provide multitenancy you better use HTTP host/TLS SNI headers.

So to make it short: Renaming the "suboperator" field into "brand" or "brandname" would be the best option ;)

**Comment by simonphilips** [comment]
There were two use-cases:

1. The operator of the platform (see credentials endpoint) is not the same as the visual operator towards the driver (example: an AC branding and DC branding in the same company). For this, there is the extra operator field.

2. Sometimes an operator acts as a front for other smaller independent operators (e.g. like a hub). He may still wish to pass on that information.

I like the idea of a simple 'brand : BusinessDetails' field, it is very clear what it means: that what the driver is supposed to see. The problem is that both the operator and suboperator fields also have some special-case purpose. We should indicate clearly that the displayed branding to the driver has the following priority, and when one is not defined, it falls back to the next: 

1. brand field
2. suboperator field
3. operator field
4. operator from credentials

It becomes a bit complex though.

**Comment by simonschllng** [comment]
> It becomes a bit complex though.

Especially for cases where the operator wands to display it in the way **`operator` powered by `suboperator`**. The brand field simply adds more uncertainty to the question what to display how.

**Comment by mbayings** [comment]
What do we do? I am fine adding a field "BrandName", but only if we can keep it simple. Can't we make this a field with default 'blank', so that it is always used, but if not filled with data is shows nothing... So then it must be used by NSPs and for SPs who show this data to the users, but it is possible that nothing is shown if it is blank.

**Comment by ahzf** [comment]
We added the field "BrandName" to our own protocol and as an extension to OICP for special partners and seem to understand it without any explanation.

At the moment I still can not find a definition of the concept/term "suboperator" using a GitHub search in this repository. Therefore, in my eyes, all arguments regarding this lose automatically. What is not documented does not exist ;)

"operator from credentials" is implicit. Everyone is allowed to do implicit things... in private. A protocol should do things explicitly or things will become complicated when it is suddenly important _who_ is saying something and not _what_ someone is saying. Testing for every result of an implicit assumption is very hard and once a behavior is out in running systems it is unlikely to change again. So very soon everything implicit will lead to different dialects instead of one common protocol.

**Comment by mbayings** [comment]
@ahzf You ar right that it is currently not clear. This is one of the things we will solve in the new version. Where it is now the proposal to add "owner" as business details with logo and name. That way branding can be solved with an owner logo. We will also describe clearly the difference when to use subco and when to use the branding.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed as discussed in: https://github.com/ocpi/ocpi/issues/83
