### ISSUE TITLE
Remote Commands (2.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#78]
Commands (they will include Connector ID):
Start/Stop
ReserveNow (not scheduling a reservation)
UnlockConnector (for MSP usage in case of emergency)
Set Charge profile (see also no 10)
Questions: Do we want these to work synchronize? Response from charge point (or timeout) might take a couple of minutes. Asynchronize might be the best solution.

**Comment by simonschllng** [comment]
In my opinion this is also strongly connected with #77.

**Comment by simonschllng** [comment]
Shouldn't **Start/Stop**, **ReserveNow** and **UnlockConnector** be implicit after the authorization or a method of the authorization request? Or is the authorization not starting the charging process directly?

A different way of implementing it, could be, that the authorization returns a kind of "general authorization token", which then can be used to trigger those commands. On the other hand, it could also simply be part of the session.

> Questions: Do we want these to work synchronize? Response from charge point (or timeout) might take a couple of minutes. Asynchronize might be the best solution.

In OCHP, the "session" is used to send status notifications from CPO to MSP. This way, it is implementing those commands asynchronous.

**Comment by RobertdeLeeuw-IHomer** [comment]
OCPP requires the Remote Command to contain a Token ID. That Charge Point will most likely do an Authorization request for this Token ID, no reason to do an authorize in OCPI before this. 

Why would you want to authorize an UnlockConnector? This is not a command that should be given to an end-user, it is only for the eMSP to help their customer when he has problems unlocking his connector. normally the connector should unlock after stopping of the connector. But due to mechanical stress on the unlock mechanism it might fail initially. The UnlockConnector can then help..

**Comment by RobertdeLeeuw-IHomer** [comment]
Biggest question to solve for remote commands: Is this a separate module with its own end-point? Or do we make the commands part of the location/session end-point?

In other words, what will the URL look like if you want to start a transaction?
https://www.server.com/ocpi/cpo/2.0/locations/NL/TNM/1012/3255/starttransaction
or
https://www.server.com/ocpi/cpo/2.0/commands/starttransaction

Giving the remote commands there own end-points makes them optional, a CPO has the option to implement them. If we make them part of Location/Session they become required if you implement these end-points.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added with a number of commits
