### ISSUE TITLE
Charge Profile (usable for Smart Charging) (10.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#80]
Also used in https://github.com/ocpi/ocpi/issues/78 (remote commands)

**Comment by finetuned89** [comment]
The message format of Smart Charging messages is the Elaad OCPI Draft 4:

```
{
"evse_id": "NL-EVN-E32492-13217",
"subscription_id": "1282",
"schedule": {
"duration": "60",
"start_schedule": "2016-02-01T10:18:00Z",
"chargingschedule_periods": [
 {
   "max_current": "10",
   "start_period": "0"
 }
]
},
"contract_id": "NL-GFX-000007-X",
"tariff_type": "D1"
}
```

In this format, one specifies when the charge profile should start (start_schedule), how long the charge profile is active (in minutes), and one can define multiple periods with different currents. The start_period is the number of minutes after start_schedule.

**Comment by Mygyll** [comment]
I think the request message should loose the subscription_id fields (as mentioned deprecated in 2.0 ) and gain a field profile_identifier. 

Instead of the async response message with NDR messages, we can use a PUT/POST endpoint:
 ~/ocpi/emsp/2.0/chargingprofiles/{id}

**Request message example:**
{
"evse_id": "NL-EVN-E32492-13217",
"chargeprofile_id": "1282",
"schedule": {
"duration": "60",
"start_schedule": "2016-02-01T10:18:00Z",
"chargingschedule_periods": [
 {
   "max_current": "10",
   "start_period": "0"
 }
]
},
"contract_id": "NL-GFX-000007-X",
"tariff_type": "D1"
}

**Response message example:**
{
    "contract_id": "NL-GFX-000007-X", 
    "event_type": "charging_profile_accepted", 
    "evse_id": "NL-EVN-E32492-13217", 
    "operator": "EVnetNL", 
    "chargeprofile_id": "1282"
}

**Comment by RobertdeLeeuw-IHomer** [comment]
Same question as for Remote Commands:
Big question to solve for Charge Profiles: Is this a separate module with its own end-point? Or do we make the Charge Profiles part of the session end-point? You can only change the profile of an ongoing session.

In other words, what will the URL look like if you want to start a transaction?
https://www.server.com/ocpi/cpo/2.0/sessions/NL/TNM/101/setchargeprofile
or
https://www.server.com/ocpi/cpo/2.0/chargeprofile

Giving the Charge Profile its own end-points makes it optional, a CPO has the option to implement it. If we make them part of Sessions it become required if you implement Sessions.

**Comment by RobertdeLeeuw-IHomer** [comment]
Charging Profiles has been added to OCPI 2.2 (RC1)

**Comment by thanaParis** [comment]
Why are OCPI ChargingProfile objects OCPP ChargingSchedule objects? Wouldn't it make sense to name them ChargingSchedules in OCPI as well?
Also, what is the recommended manner for a CPO to construct a OCPP ChargingProfile object? Some of the fields can be deduced from the context of a ChargingProfiles Receiver PUT request, others cannot:
{
    chargingProfileId, (???)
    transactionId, (sessionId)
    stackLevel, (???)
    chargingProfilePurpose, (TxProfile)
    chargingProfileKind, (Relative)
    ... (Unneeded optional fields),
    chargingSchedule (Same pdu as an OCPI ChargingProfile)
}

chargingProfileId and stackLevel are required, and stackLevel at a minimum must be stored by the CPO in some manner correlated to the OCPI Charging Profile/Session in order to perform the ChargingProfiles Receiver DELETE request later (since ClearChargingProfile.req needs either chargingProfileId + stackLevel or stackLevel + connectorId + chargingProfilePurpose).

**Comment by RobertdeLeeuw-IHomer** [comment]
The charging profiles provide via OCPI are input for the CPO, it is up to the CPO if they want to use this information as is, or combine it with other inputs to create their own profiles. 
That is the reason the StackLevel and ChargingProfileID are not provided via OCPI. They have to be create by the CPO. Otherwise the SCSP could overwrite profiles they have not set. 
If only the SCSP provides input to the CPO, the CPO could set the ChargingProfileId and Stacklevel always to 1.

**Comment by thanaParis** [comment]
That makes sense when the ChargingProfile Receiver PUT is used exclusively for creating a charging profile. The endpoint mentions being able to update a profile though, both on a session and an evse. How is that meant to work, given the eMSP/SCSP has no way to refer to a specific ChargingProfile known by the CPO (As in, no ChargingProfileId--there's no uniquely identifying required input of any kind in an OCPI ChargingProfile)? Is the expected behavior that a CPO only lets an eMSP/SCSP set a single profile of each type possible on an EVSE (So, a PUT with a start_date_time field overrides/'updates' any other absolute profiles on the target evse set by that client)?

**Comment by RobertdeLeeuw-IHomer** [comment]
@thanaParis yes, only one profile was the idea. Multple profiles are already rare for CPOs to use, as the SCSP provides input to the CPO, the idea at the time of writing was that that would be sufficient. And I currently have not learned to that would be limiting for somebody.
